#!/bin/bash

source $(dirname $)/config

batStatus=$(acpi --battery | awk '{gsub(/,/, ""); print $3}')
batLevel=$(acpi --battery | awk '{gsub(/[,%]/, ""); print $4}')

output=""

if [[ -z $batStatus ]]; then
    echo -e "${GRAY} \uf1e6"

elif [[ $batStatus == Charging ]]; then
    if [[ $batLevel -gt 80 ]]; then
        output="${GREEN} \uf240"
    elif [[ $batLevel -gt 60 ]]; then
        output="${GREEN1} \uf241"
    elif [[ $batLevel -gt 40 ]]; then
        output="${GREEN2} \uf242"
    elif [[ $batLevel -gt 20 ]]; then
        output="${GREEN3} \uf243"
    else
        output="${GREEN4} \uf244"
    fi
    echo -e "$output $batLevel%"

elif [[ $batStatus == Discharging ]]; then
    if [[ $batLevel -gt 80 ]]; then
        output="${GREEN1} \uf240"
    elif [[ $batLevel -gt 60 ]]; then
        output="${GREEN2} \uf241"
    elif [[ $batLevel -gt 40 ]]; then
        output="${GREEN3} \uf242"
    elif [[ $batLevel -gt 20 ]]; then
        output="${GREEN4} \uf243"
    else
        output="${RED} \uf244"
    fi
    echo -e "$output $batLevel%"

elif [[ $batStatus == Full ]]; then
    echo -e "${GREEN} \uf240 $batLevel%"
fi
