#!/bin/bash
wired=$(cat /sys/class/net/enp0s31f6/carrier 2>/dev/null)
wifi=$(cat /sys/class/net/wlp58s0/carrier 2>/dev/null)

if [[ $wired -eq 1 ]]; then
    echo -e '\uf0ac'
elif [[ $wifi -eq 1 ]] && [[ $wired -ne 1 ]]; then
    echo -e '\uf1eb'
fi
