#!/bin/bash
# base panel script:
# https://github.com/baskerville/bspwm/blob/master/examples/panel/panel

cd $(dirname $0)
source $(dirname $)/config

#
# Main
#

if [[ $(pgrep -cx panel) -gt 1 ]]; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[[ -e $PANEL_FIFO ]] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding "$PANEL_HEIGHT"
bspc subscribe report > "$PANEL_FIFO" &

while true; do
	echo "S""${YELLOW} $(./clock)" > "$PANEL_FIFO"
	sleep 0.1s
done &

./panel_bar < "$PANEL_FIFO" | lemonbar \
    -f "FontAwesome:size=10" \
    -f "Droid Sans:size=10" \
    x"$PANEL_HEIGHT" -F "$COLOUR_FOREGROUND" -B "$COLOUR_BACKGROUND" &

wait
# vim: set ft=sh:
