#!/bin/sh

bspc config border_width 1
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config remove_disabled_monitors true

bspc config split_ratio 0.50

bspc monitor LVDS1 -d I II III IV V
bspc monitor HDMI1 -d VI VII VIII IX X

# Startup Shits
~/.config/bspwm/panel/panel &
sxhkd &

~/.config/bspwm/startup &

# Java things
wmname LG3D
